---
# tasks file for roles/install-docker-opensuse

- name: Install docker and docker-compose
  zypper:
    name:
      - docker
      - docker-compose
    state: present
    update_cache: yes

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add docker group to user
  user:
    name: erviejohn
    group: docker
    append: yes

- name: Install pyhton3 and python3-pip
  zypper:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Install docker-py using pip
  pip:
    name: docker-py

- name: Start and Enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes

