---
# tasks file for roles/centos-nagios

- name: Install Prerequisites of Nagios
  yum:
    name: 
      - httpd 
      - php
      - gcc
      - glibc
      - glibc-common
      - wget
      - perl
      - gd
      - gd-devel 
      - unzip 
      - zip
      - tar
    update_cache: yes

- name: Create nagios group
  group:
    name: group-nagios
    state: present

- name: Create nagios user
  user:
    name: ervie-nagios
    comment: New user ervie-nagios
    group: group-nagios

- name: Append group-nagios to apache
  user: 
    name: apache
    group: group-nagios

- name: Download nagios
  get_url:
    url: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz
    dest: /tmp/

- name: Extract the files
  unarchive:
    src: /tmp/nagios-4.4.5.tar.gz
    dest: /tmp/
    remote_src: yes
  register: extract_nagios

- name: Compile nagios
  shell:
    chdir: /tmp/nagios-4.4.5/
    cmd: "./configure"
#    cmd: "./configure --with-httpd_conf=/etc/apache2/sites-enabled/"
  when: extract_nagios.changed

- name: re compile all
  make:
    chdir: /tmp/nagios-4.4.5/
    target: all
  when: extract_nagios.changed

- name: install-groups-users in /tmp/nagios-4.4.5/ file
  make:
    chdir: /tmp/nagios-4.4.5/
    target: install-groups-users
  when: extract_nagios.changed

- name: run install
  make:
    chdir: /tmp/nagios-4.4.5/
    target: install
  when: extract_nagios.changed

#- name: install-daemoninit in /tmp/nagios-4.4.5 file
#  make:
#    chdir: /tmp/nagios-4.4.5/
#    target: install-daemoninit
#  when: extract_nagios.changed

- name: install-config in /tmp/nagios-4.4.5 file
  make:
    chdir: /tmp/nagios-4.4.5/
    target: install-config
  when: extract_nagios.changed    

- name: install-commandmode in /tmp/nagios-4.4.5 file
  make:
    chdir: /tmp/nagios-4.4.5/
    target: install-commandmode
  when: extract_nagios.changed

- name: install nagios web interface
  make:
    chdir: /tmp/nagios-4.4.5/
    target: install-webconf
  when: extract_nagios.changed

- name: install passlib using pip
  pip:
    name: passlib

- name: Create htpasswd file
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: ervie-admin-centos
    password: erviejohn20
#    crypt_scheme: md5_cryptic

- name: Configure email in /usr/local/nagios/etc/objects/contacts.cfg file
  replace:
    path: /usr/local/nagios/etc/objects/contacts.cfg
    regexp: '.email(.*)$'
    replace: 'email		erviejohn.villareal79@gmail.com'
  when: extract_nagios.changed

- name: Download Nagios Plugins
  get_url:
    url: https://nagios-plugins.org/download/nagios-plugins-2.2.1.tar.gz
    dest: /tmp/nagios-plugins-2.2.1.tar.gz
  register: download_plugins

- name: Extract the nagios plugins
  unarchive:
    src: /tmp/nagios-plugins-2.2.1.tar.gz
    dest: /tmp/
    remote_src: yes
  when: download_plugins.changed

- name: Compile nagios plugins
  shell:
    chdir: /tmp/nagios-plugins-2.2.1
    cmd: "./configure"
  when: download_plugins.changed

- name: build the default nagios plugins
  make:
    chdir: /tmp/nagios-plugins-2.2.1/
  when: download_plugins.changed

- name: install in nagios plugins
  make:
    chdir: /tmp/nagios-plugins-2.2.1/
    target: install
  when: download_plugins.changed

- name: Reload system service
  systemd:
    daemon-reload: yes

- name: Start Nagios
  systemd:
    state: started
    name: nagios
    enabled: yes

- name: add http in firewall
  firewalld:
    service: http
    permanent: true
    state: enabled
  register: add_http

- name: Reload service firewalld
  systemd:
    name: firewalld
    state: reloaded  
  when: add_http.changed
