---

# Install and Configure ELK on Ubuntu and Centos

- name: Stop firewall service on ubuntu and centos
  hosts: all
  tasks:
    - name: Stop ufw on ubuntu
      service:
        name: ufw
        state: stopped
        enabled: no
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Stop firewalld on centos
      service:
        name: firewalld
        state: stopped
        enabled: no
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Elastic Stack (Elasticsearch, Kibana and Logstash) on Ubuntu
  hosts: ubuntu
  roles:
    - ubuntu-Elasticsearch
    - ubuntu-Kibana
    - ubuntu-Logstash

- name: Install Elastic Stacj (Elasticsearch, Kibana, and Logstash) on CentOS
  hosts: centos
  roles:
    - centos-Elasticsearch
    - centos-Kibana
    - centos-Logstash  
