---
# tasks file for roles/centos-grafana

- name: Add grafana yum repository
  copy:
    src: config_files/grafana.repo
    dest: /etc/yum.repos.d/grafana.repo

- name: Install makecache and grafana with yum
  yum:
    name: 
      - grafana
    state: present
    update_cache: yes

- name: Start and Enable grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: Open firewall port for grafana
  firewalld:
    port: 3000/tcp
    permanent: true
    state: enabled

- name: Reload firewalld 
  systemd:
    name: firewalld
    state: reloaded
