---

# Install Elastic Stack in a Containerize from on Ubuntu and Centos

- name: Stop firewall service on ubuntu and centos
  hosts: all
  tasks:
    - name: Stop ufw on ubuntu
      service:
        name: ufw
        state: stopped
        enabled: no
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Stop firewalld on centos
      service:
        name: firewalld
        state: stopped
        enabled: no
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install docker on Ubuntu
  hosts: ubuntu
  roles: 
    - ubuntu-install-docker

- name: Install docker on Centos
  hosts: centos
  roles: 
    - centos-install-docker

- name: Pull Elastic Stack Images and Run
  hosts: all
  roles: 
    - install-ElasticStack-docker
