---

- name: Stop firewall service on ubuntu and centos
  hosts: all
  tasks:
    - name: Stop ufw on ubuntu
      service:
        name: ufw
        state: stopped
        enabled: no
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Stop firewalld on centos
      service:
        name: firewalld
        state: stopped
        enabled: no
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install and Configure Grafana with Prometheus on Ubuntu
  hosts: ubuntu
  roles:
     - ubuntu-grafana
     - ubuntu-prometheus

- name: Install and Configure Grafana with Prometheus on CentOS
  hosts: centos
  roles:
    - centos-grafana
    - centos-prometheus

- name: Install and Configure Grafana with Prometheus on Ubuntu
  hosts: ubuntu
  roles:
    - ubuntu-telegraf

- name: Install and Configure Grafana with Prometheus on CentOS
  hosts: centos
  roles:
    - centos-telegraf
